var dummydata = [
  {
    "PrimaryEventCode": "",
    "Recordnumber": 0,
    "NetworkName": 5,
    "TimeBand": "NON-IMPACT",
    "SponsorTypeName": "NON PRIME",
    "ProgramName": "ROS",
    "StartTime": "",
    "EndTime": "10:00:00",
    "Rate": "17:59:59",
    "Seconds": 5100,
    "Amount": 11370,
    "ValuationRate": 5798700,
    "BookedSeconds": 5100,
    "BalanceSeconds": 9960,
    "Sun": 1410,
    "Mon": 0,
    "Tue": 1,
    "Wed": 1,
    "Thu": 1,
    "Fri": 1,
    "Sat": 1,
    "RevFlag": 0,
    "AccountName": 1,
    "EventName": "",
    "Spots": "",
    "PaymentModeCaption": 416,
    "RevenueTypeName": "60 DAYS CREDIT",
    "SubRevenueTypeName": "Ad Revenue",
    "ProgramCategoryName": "",
    "SponsorTypeCode": "",
    "ProgramCode": "ZAROS00001",
    "ProgramCategoryCode": "",
    "bandcode": "",
    "netcode": "NON PRIME",
    "AccountCode": 6,
    "EventCode": "",
    "RevenueTypeCode": "",
    "subrevenuetypecode": "I000100001",
    "locationname": 0,
    "channelname": "ASIA",
    "DealNumber": "ZEE TV",
    "clientname": "61/2023",
    "agencyname": "COCA COLA INDIA PVT. LTD",
    "DealStartDate": "MEDIACOM COMM (HAR)",
    "DealEndDate": "01-02-2023",
    "RecoTakenOn": "31-05-2023",
    "DealValuationAmount": "21-04-2023 16:16",
    "BookedAmount": 5798700,
    "BookedValuationAmount": 5079600,
    "BalanceAmount": 5079600,
    "BalanceValuationAmount": 719100,
    "countbased": 719100,
    "baseduration": 0,
    "Locationcode": 10,
    "channelcode": "ZAZEE00001"
  },
  {
    "PrimaryEventCode": "",
    "Recordnumber": 0,
    "NetworkName": 6,
    "TimeBand": "NON-IMPACT",
    "SponsorTypeName": "NON PRIME",
    "ProgramName": "ROS",
    "StartTime": "",
    "EndTime": "10:30:00",
    "Rate": "10:59:59",
    "Seconds": 6000,
    "Amount": 3150,
    "ValuationRate": 1890000,
    "BookedSeconds": 6000,
    "BalanceSeconds": 1400,
    "Sun": 1750,
    "Mon": 0,
    "Tue": 1,
    "Wed": 1,
    "Thu": 1,
    "Fri": 1,
    "Sat": 1,
    "RevFlag": 0,
    "AccountName": 1,
    "EventName": "",
    "Spots": "",
    "PaymentModeCaption": 60,
    "RevenueTypeName": "60 DAYS CREDIT",
    "SubRevenueTypeName": "Ad Revenue",
    "ProgramCategoryName": "",
    "SponsorTypeCode": "",
    "ProgramCode": "ZAROS00001",
    "ProgramCategoryCode": "",
    "bandcode": "",
    "netcode": "NON PRIME",
    "AccountCode": 6,
    "EventCode": "",
    "RevenueTypeCode": "",
    "subrevenuetypecode": "I000100001",
    "locationname": 0,
    "channelname": "ASIA",
    "DealNumber": "ZEE TV",
    "clientname": "61/2023",
    "agencyname": "COCA COLA INDIA PVT. LTD",
    "DealStartDate": "MEDIACOM COMM (HAR)",
    "DealEndDate": "01-02-2023",
    "RecoTakenOn": "31-05-2023",
    "DealValuationAmount": "21-04-2023 16:16",
    "BookedAmount": 1890000,
    "BookedValuationAmount": 840000,
    "BalanceAmount": 840000,
    "BalanceValuationAmount": 1050000,
    "countbased": 1050000,
    "baseduration": 0,
    "Locationcode": 10,
    "channelcode": "ZAZEE00001"
  },
  {
    "PrimaryEventCode": "",
    "Recordnumber": 0,
    "NetworkName": 7,
    "TimeBand": "NON-IMPACT",
    "SponsorTypeName": "NON PRIME",
    "ProgramName": "ROS",
    "StartTime": "",
    "EndTime": "11:00:00",
    "Rate": "11:29:59",
    "Seconds": 8000,
    "Amount": 3150,
    "ValuationRate": 2520000,
    "BookedSeconds": 8000,
    "BalanceSeconds": 1345,
    "Sun": 1805,
    "Mon": 0,
    "Tue": 1,
    "Wed": 1,
    "Thu": 1,
    "Fri": 1,
    "Sat": 1,
    "RevFlag": 0,
    "AccountName": 1,
    "EventName": "",
    "Spots": "",
    "PaymentModeCaption": 56,
    "RevenueTypeName": "60 DAYS CREDIT",
    "SubRevenueTypeName": "Ad Revenue",
    "ProgramCategoryName": "",
    "SponsorTypeCode": "",
    "ProgramCode": "ZAROS00001",
    "ProgramCategoryCode": "",
    "bandcode": "",
    "netcode": "NON PRIME",
    "AccountCode": 6,
    "EventCode": "",
    "RevenueTypeCode": "",
    "subrevenuetypecode": "I000100001",
    "locationname": 0,
    "channelname": "ASIA",
    "DealNumber": "ZEE TV",
    "clientname": "61/2023",
    "agencyname": "COCA COLA INDIA PVT. LTD",
    "DealStartDate": "MEDIACOM COMM (HAR)",
    "DealEndDate": "01-02-2023",
    "RecoTakenOn": "31-05-2023",
    "DealValuationAmount": "21-04-2023 16:16",
    "BookedAmount": 2520000,
    "BookedValuationAmount": 1076000,
    "BalanceAmount": 1076000,
    "BalanceValuationAmount": 1444000,
    "countbased": 1444000,
    "baseduration": 0,
    "Locationcode": 10,
    "channelcode": "ZAZEE00001"
  },
  {
    "PrimaryEventCode": "",
    "Recordnumber": 0,
    "NetworkName": 8,
    "TimeBand": "NON-IMPACT",
    "SponsorTypeName": "NON PRIME",
    "ProgramName": "ROS",
    "StartTime": "",
    "EndTime": "11:30:00",
    "Rate": "11:59:59",
    "Seconds": 8000,
    "Amount": 2220,
    "ValuationRate": 1776000,
    "BookedSeconds": 8000,
    "BalanceSeconds": 560,
    "Sun": 1660,
    "Mon": 0,
    "Tue": 1,
    "Wed": 1,
    "Thu": 1,
    "Fri": 1,
    "Sat": 1,
    "RevFlag": 0,
    "AccountName": 1,
    "EventName": "",
    "Spots": "",
    "PaymentModeCaption": 23,
    "RevenueTypeName": "60 DAYS CREDIT",
    "SubRevenueTypeName": "Ad Revenue",
    "ProgramCategoryName": "",
    "SponsorTypeCode": "",
    "ProgramCode": "ZAROS00001",
    "ProgramCategoryCode": "",
    "bandcode": "",
    "netcode": "NON PRIME",
    "AccountCode": 6,
    "EventCode": "",
    "RevenueTypeCode": "",
    "subrevenuetypecode": "I000100001",
    "locationname": 0,
    "channelname": "ASIA",
    "DealNumber": "ZEE TV",
    "clientname": "61/2023",
    "agencyname": "COCA COLA INDIA PVT. LTD",
    "DealStartDate": "MEDIACOM COMM (HAR)",
    "DealEndDate": "01-02-2023",
    "RecoTakenOn": "31-05-2023",
    "DealValuationAmount": "21-04-2023 16:16",
    "BookedAmount": 1776000,
    "BookedValuationAmount": 448000,
    "BalanceAmount": 448000,
    "BalanceValuationAmount": 1328000,
    "countbased": 1328000,
    "baseduration": 0,
    "Locationcode": 10,
    "channelcode": "ZAZEE00001"
  },
  {
    "PrimaryEventCode": "",
    "Recordnumber": 0,
    "NetworkName": 9,
    "TimeBand": "NON-IMPACT",
    "SponsorTypeName": "NON PRIME",
    "ProgramName": "ROS",
    "StartTime": "",
    "EndTime": "12:00:00",
    "Rate": "12:29:59",
    "Seconds": 8000,
    "Amount": 2220,
    "ValuationRate": 1776000,
    "BookedSeconds": 8000,
    "BalanceSeconds": 560,
    "Sun": 1660,
    "Mon": 0,
    "Tue": 1,
    "Wed": 1,
    "Thu": 1,
    "Fri": 1,
    "Sat": 1,
    "RevFlag": 0,
    "AccountName": 1,
    "EventName": "",
    "Spots": "",
    "PaymentModeCaption": 23,
    "RevenueTypeName": "60 DAYS CREDIT",
    "SubRevenueTypeName": "Ad Revenue",
    "ProgramCategoryName": "",
    "SponsorTypeCode": "",
    "ProgramCode": "ZAROS00001",
    "ProgramCategoryCode": "",
    "bandcode": "",
    "netcode": "NON PRIME",
    "AccountCode": 6,
    "EventCode": "",
    "RevenueTypeCode": "",
    "subrevenuetypecode": "I000100001",
    "locationname": 0,
    "channelname": "ASIA",
    "DealNumber": "ZEE TV",
    "clientname": "61/2023",
    "agencyname": "COCA COLA INDIA PVT. LTD",
    "DealStartDate": "MEDIACOM COMM (HAR)",
    "DealEndDate": "01-02-2023",
    "RecoTakenOn": "31-05-2023",
    "DealValuationAmount": "21-04-2023 16:16",
    "BookedAmount": 1776000,
    "BookedValuationAmount": 448000,
    "BalanceAmount": 448000,
    "BalanceValuationAmount": 1328000,
    "countbased": 1328000,
    "baseduration": 0,
    "Locationcode": 10,
    "channelcode": "ZAZEE00001"
  }
];

var dummyProgram = [
  {
    "Telecastdate": "",
    "BookedSpots": "21-04-2023",
    "StartTime": 0,
    "EndTime": "10:00:00",
    "ProgramName": "17:59:59",
    "AvailableDuration": ""
  },
  {
    "Telecastdate": "",
    "BookedSpots": "24-04-2023",
    "StartTime": 0,
    "EndTime": "10:00:00",
    "ProgramName": "17:59:59",
    "AvailableDuration": ""
  },
  {
    "Telecastdate": "",
    "BookedSpots": "25-04-2023",
    "StartTime": 0,
    "EndTime": "10:00:00",
    "ProgramName": "17:59:59",
    "AvailableDuration": ""
  },
  {
    "Telecastdate": "",
    "BookedSpots": "26-04-2023",
    "StartTime": 0,
    "EndTime": "10:00:00",
    "ProgramName": "17:59:59",
    "AvailableDuration": ""
  },
  {
    "Telecastdate": "",
    "BookedSpots": "27-04-2023",
    "StartTime": 0,
    "EndTime": "10:00:00",
    "ProgramName": "17:59:59",
    "AvailableDuration": ""
  },
  {
    "Telecastdate": "",
    "BookedSpots": "28-04-2023",
    "StartTime": 0,
    "EndTime": "10:00:00",
    "ProgramName": "17:59:59",
    "AvailableDuration": ""
  }
];
